input {

  file {

    path => "/logs/*.log"

    start_position => "beginning"
  }
}

filter {

  grok {

    match => {
      "message" => "%{GREEDYDATA:log_message}"
    }
  }
}

output {

  elasticsearch {

    hosts => ["http://elasticsearch:9200"]

    index => "enterprise-logs"
  }
}
