global:

  scrape_interval: 30s

rule_files:

  - "/etc/prometheus/rules/business-kpi-alert-rules.yml"

scrape_configs:

  - job_name: "business-kpis"

    static_configs:

      - targets:
          - "business-system:9100"
